name: Build binaries, build container images, push to registry, deploy to gke

on:
  workflow_run:
    workflows:
      - Integration tests
    branches: [master]
    types:
      - completed

env:
  IMAGE: dingir
  GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install system depenencies
        run: |-
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt install yq libpq-dev cmake gcc g++ postgresql-client-12
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target x86_64-unknown-linux-gnu --release
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GKE_SERVICE_TOKEN }}
          project_id: ${{ secrets.GCLOUD_PROJECT }}
          # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |-
          gcloud --quiet auth configure-docker
      - uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: ${{ secrets.BITRAW_GKE_CLUSTER }}
          location: ${{ secrets.BITRAW_GKE_ZONE }}
          credentials: ${{ secrets.GKE_SERVICE_TOKEN }}
      - name: Build containers
        run: |-
          docker build . --tag "gcr.io/$GCLOUD_PROJECT/$IMAGE-matchengine:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            -f release/Dockerfile.matchengine
          docker build . --tag "gcr.io/$GCLOUD_PROJECT/$IMAGE-persistor:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            -f release/Dockerfile.persistor
          docker build . --tag "gcr.io/$GCLOUD_PROJECT/$IMAGE-restapi:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            -f release/Dockerfile.restapi
      - name: Publish
        run: |-
          docker push "gcr.io/$GCLOUD_PROJECT/$IMAGE-matchengine:$GITHUB_SHA"
          docker push "gcr.io/$GCLOUD_PROJECT/$IMAGE-persistor:$GITHUB_SHA"
          docker push "gcr.io/$GCLOUD_PROJECT/$IMAGE-restapi:$GITHUB_SHA"
      - name: Deploy
        run: |-
          kubectl delete configmap envoy-files-config -n default
          kubectl create configmap envoy-files-config --from-file=orchestra/proto/exchange/matchengine.pb --from-file=orchestra/docker/envoy.yaml -n default
          REPO=gcr.io/$GCLOUD_PROJECT/$IMAGE-matchengine:$GITHUB_SHA yq e -i '.spec.template.spec.containers[0].image = strenv(REPO)' kubernetes/matchengine-deployment.yaml
          REPO=gcr.io/$GCLOUD_PROJECT/$IMAGE-persistor:$GITHUB_SHA yq e -i '.spec.template.spec.containers[0].image = strenv(REPO)' kubernetes/persistor-deployment.yaml
          REPO=gcr.io/$GCLOUD_PROJECT/$IMAGE-restapi:$GITHUB_SHA yq e -i '.spec.template.spec.containers[0].image = strenv(REPO)' kubernetes/restapi-deployment.yaml
          kubectl apply -f kubernetes/matchengine-deployment.yaml
          kubectl apply -f kubernetes/persistor-deployment.yaml
          kubectl apply -f kubernetes/restapi-deployment.yaml
          kubectl rollout restart deployment exchange-envoy
